language: python
python:
  - "2.7"
sudo: required
before_install:
  - mkdir siux
  - wget https://raw.githubusercontent.com/eSiUX/siux-python/master/siux/siuxmethodlib.py -O siux/siuxmethodlib.py
  - wget https://raw.githubusercontent.com/eSiUX/siux-python/master/siux/siuxlib.py -O siux/siuxlib.py
before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD/siux
# command to run tests
script: nosetests
